version: 2

jobs:
  failed_flag_failure:
    docker:
      - image: busybox:latest
    steps:
      - checkout
      - run: false || echo 'export FAILED=1' >> $BASH_ENV
      - run: true || echo 'export FAILED=1' >> $BASH_ENV
      - run: false || echo 'export FAILED=1' >> $BASH_ENV
      - run: |
          [ -e $BASH_ENV ] && . $BASH_ENV
          ! [ -n "$FAILED" ]
  failed_flag_success:
    docker:
      - image: busybox:latest
    steps:
      - checkout
      - run: true || echo 'export FAILED=1' >> $BASH_ENV
      - run: |
          [ -e $BASH_ENV ] && . $BASH_ENV
          ! [ -n "$FAILED" ]
  failed_flag_env_failure:
    docker:
      - image: busybox:latest
    steps:
      - checkout
      - run: false || .circleci/env save FAILED
      - run: true || .circleci/env save FAILED
      - run: false || .circleci/env save FAILED
      - run: '! .circleci/env exists FAILED'
  failed_flag_env_success:
    docker:
      - image: busybox:latest
    steps:
      - checkout
      - run: true || .circleci/env save FAILED
      - run: '! .circleci/env exists FAILED'
  when_always_failure:
    docker:
      - image: busybox:latest
    steps:
      - checkout
      - run:
          command: 'false'
          when: always
      - run:
          command: 'true'
          when: always
      - run:
          command: 'false'
          when: always
  when_always_success:
    docker:
      - image: busybox:latest
    steps:
      - checkout
      - run:
          command: 'true'
          when: always
workflows:
  version: 2
  all:
    jobs:
      - failed_flag_failure
      - failed_flag_success
      - failed_flag_env_failure
      - failed_flag_env_success
      - when_always_failure
      - when_always_success
